feat(test,bump): Added bump job summary and checks, Added pytest workflow (#45)
Co-authored-by: qte77 <qte@77>

diff --git a/.github/workflows/bump-my-version.yaml b/.github/workflows/bump-my-version.yaml
--- a/.github/workflows/bump-my-version.yaml
+++ b/.github/workflows/bump-my-version.yaml
@@ -1,5 +1,5 @@
 ---
-name: "bump-my-version"
+name: bump_my_version
 
 on:
   # pull_request:
@@ -17,12 +17,20 @@ on:
         - 'minor'
         - 'patch'
 
+      # FIXME remove
+      # debug_fail_on_purpose:
+      #   description: ""
+      #   required: true
+      #   default: false
+      #   type: boolean
+      # FIXME remove
+
 env:
   BRANCH_NEW: "bump-${{ github.run_number }}-${{ github.ref_name }}"
   SKIP_PR_HINT: "[skip ci bump]"
 
 jobs:
-  bump-my-version:
+  bump_my_version:
     # TODO bug? currently resulting in: Unrecognized named-value: 'env'.
     # https://stackoverflow.com/questions/61238849/github-actions-if-contains-function-not-working-with-env-variable/61240761
     # if: !contains(
@@ -36,6 +44,9 @@ jobs:
         ( github.event.pull_request.merged == true &&
         github.event.pull_request.closed_by != 'github-actions' )
     runs-on: ubuntu-latest
+    outputs:
+      branch_new: ${{ steps.create_new_branch.outputs.branch_new }}
+      summary_data: ${{ steps.set_summary.outputs.summary_data }}
     permissions:
       actions: read
       checks: write
@@ -49,11 +60,12 @@ jobs:
           fetch-depth: 1
 
       - name: Create new branch
-        id: branch
+        id: create_new_branch
         run: |
           git config user.email "bumped@qte77.gha"
           git config user.name "bump-my-version"
-          git checkout -b ${{ env.BRANCH_NEW }}
+          git checkout -b "${{ env.BRANCH_NEW }}"
+          echo "branch_new=${{ env.BRANCH_NEW }}" >> $GITHUB_OUTPUT
 
       - name: Bump version
         id: bump
@@ -71,30 +83,53 @@ jobs:
           VER_CURRENT: ${{ steps.bump.outputs.current-version }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          tag_current="v${{ env.VER_CURRENT }}"
+          pr_title="PR ${{ env.BRANCH_NEW }} ${{ env.SKIP_PR_HINT }}"
+          pr_body="PR automatically created from \`${{ github.ref_name }}\` to bump from \`${{ env.VER_PREVIOUS }}\` to \`${{ env.VER_CURRENT }}\` on \`${{ env.BRANCH_NEW }}\`."
+          pr_body="${pr_body} Tag \`${tag_current}\` will be created and has to be deleted manually if PR get's closed without merge."
+
           gh pr create \
             --base ${{ github.ref_name }} \
             --head ${{ env.BRANCH_NEW }} \
-            --title "PR ${{ env.BRANCH_NEW }} ${{ env.SKIP_PR_HINT }}" \
-            --body "PR automatically created from `${{ github.ref_name }}` to bump from `${{ env.VER_PREVIOUS }}` to `${{ env.VER_CURRENT }}` on `${{ env.BRANCH_NEW }}`." \
+            --title "${pr_title}" \
+            --body "${pr_body}"
             # --label "bump"
 
-      - name: Delete branch and PR in case of failure
-        if: failure()
+      # FIXME remove 
+      # - name: Intentional failure
+      #   if: ${{ inputs.debug_fail_on_purpose }}
+      #   run: exit 1
+      # FIXME remove 
+
+      - name: Delete branch and PR in case of failure or cancel
+        if: failure() || cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+            branch_del_api_call="repos/${{ github.repository }}/git/refs/heads/${{ env.BRANCH_NEW }}"
+            tag_to_delete="v${{ steps.bump.outputs.current-version }}"
             del_msg="'${{ env.BRANCH_NEW }}' force deletion attempted."
-            else_msg="'${{ env.BRANCH_NEW }}' does not exist. Skipping closure."
-            pr_msg="Closing PR'${{ env.BRANCH_NEW }}' to rollback after failure"
-            echo "PR ${del_msg}."
-            gh pr close "${{ env.BRANCH_NEW }}" --comment "${pr_msg}" || \
-              echo "PR $else_msg"
+            close_msg="Closing PR '${{ env.BRANCH_NEW }}' to rollback after failure"
+
+            echo "Tag ${tag_to_delete} for ${del_msg}"
+            git tag -d  "${tag_to_delete}"
+            echo "PR for ${del_msg}"
+            gh pr close "${{ env.BRANCH_NEW }}" --comment "${close_msg}"
             echo "Branch ${del_msg}"
-            gh api "repos/${{ github.repository }}/git/refs/heads/${{ env.BRANCH_NEW }}" -X DELETE && echo "Branch deleted" || echo "Branch $else_msg"
+            gh api "${branch_del_api_call}" -X DELETE && \
+              echo "Branch without error return deleted."
+
+      - name: Set summary data
+        id: set_summary
+        if: ${{ always() }}
+        run: echo "summary_data=${GITHUB_STEP_SUMMARY}" >> $GITHUB_OUTPUT
   
   generate_summary:
     name: Generate Summary Report 
-    if: ${{ !cancelled() }}
-    needs: bump-my-version
+    if: ${{ always() }}
+    needs: bump_my_version
     uses: "./.github/workflows/summarize-jobs-reusable.yaml"
+    with:
+      branch_to_summarize: ${{ needs.bump_my_version.outputs.branch_new }}
+      summary_data: ${{ needs.bump_my_version.outputs.summary_data }}
 ...
diff --git a/.github/workflows/summarize-jobs-reusable.yaml b/.github/workflows/summarize-jobs-reusable.yaml
--- a/.github/workflows/summarize-jobs-reusable.yaml
+++ b/.github/workflows/summarize-jobs-reusable.yaml
@@ -3,6 +3,11 @@
 # FIXME currently bug in gha summaries ? $GITHUB_STEP_SUMMARY files are empty
 # https://github.com/orgs/community/discussions/110283
 # https://github.com/orgs/community/discussions/67991
+# Possible workaround
+# echo ${{ fromJSON(step).name }}" >> $GITHUB_STEP_SUMMARY
+# echo ${{ fromJSON(step).outcome }}" >> $GITHUB_STEP_SUMMARY
+# echo ${{ fromJSON(step).conclusion }}"
+
 name: Summarize workflow jobs
 
 on:
@@ -11,11 +16,14 @@ on:
       summary:
         description: "Outputs summaries of jobs in a workflow"
         value: ${{ jobs.generate_summary.outputs.summary }}
-    #inputs:
-    #  branch_to_summarize:
-    #    required: false
-    #    default: 'main'
-    #    type: string
+    inputs:
+      branch_to_summarize:
+        required: false
+        default: 'main'
+        type: string
+      summary_data:
+        required: false
+        type: string
 
 jobs:
   generate_summary:
@@ -27,64 +35,93 @@ jobs:
       checks: read
       pull-requests: none
     outputs:
-      summary: ${{ steps.changed_files.outputs.summary }}
+      summary: ${{ steps.add_changed_files.outputs.summary }}
     steps:
 
       - name: Add general information
         id: general_info
         run: |
           echo "# Job Summaries" >> $GITHUB_STEP_SUMMARY
-          echo "## Job: `${{ github.job }}` - Date: $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
+          echo "Job: `${{ github.job }}`" >> $GITHUB_STEP_SUMMARY
+          echo "Date: $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
 
       - name: Add step states
         id: step_states
         run: |
-          summary_path=$(dirname "$GITHUB_STEP_SUMMARY")
-          echo ${{ steps.general_info.outputs.summary }} >> $GITHUB_STEP_SUMMARY
           echo "### Steps:" >> $GITHUB_STEP_SUMMARY
-          for file in "$summary_path"/step_summary_*; do
-            if [ -f "$file" ]; then
-              # Check if the file is not the same as $GITHUB_STEP_SUMMARY
-              if [ "$file" != "$GITHUB_STEP_SUMMARY" ]; then
-                # Check if the file contains valid JSON
-                if jq -e . >/dev/null 2>&1 <<< "$(cat "$file")"; then
-                  # Parse and output JSON content
-                  jq -r '
-                    .steps[]
-                    | select(.conclusion != null)
-                    | "- **\(.name)**: \(
-                      if .conclusion == "success" then ":white_check_mark:"
-                      elif .conclusion == "failure" then ":x:"
-                      else ":warning:" end
-                    )"
-                  ' "$file" >> $GITHUB_STEP_SUMMARY
-                else
-                  echo "Invalid JSON in $file." >> $GITHUB_STEP_SUMMARY
-                fi
-              else
-                echo "Skipping $file as it is the same as $GITHUB_STEP_SUMMARY." >> $GITHUB_STEP_SUMMARY
-              fi
-            else
-              echo "File $file does not exist." >> $GITHUB_STEP_SUMMARY
-            fi
-          done
+          # loop summary_data if valid json
+          if jq -e . >/dev/null 2>&1 <<< "${{ inputs.summary_data }}"; then
+            jq -r '
+              .steps[]
+              | select(.conclusion != null)
+              | "- **\(.name)**: \(
+                if .conclusion == "success" then ":white_check_mark:"
+                elif .conclusion == "failure" then ":x:"
+                else ":warning:" end
+              )"
+            ' <<< "${{ inputs.summary_data }}" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Invalid JSON in summary data." >> $GITHUB_STEP_SUMMARY
+          fi
 
       - name: Checkout repo
         uses: actions/checkout@v4
         with:
-          # ref: "${{ branch_to_summarize }}"
-          fetch-depth: 2
+          ref: "${{ inputs.branch_to_summarize }}"
+          fetch-depth: 0
 
       - name: Add changed files since last push
-        id: changed_files
+        id: add_changed_files
         run: |
-          current=$(git show -s --format=%ci HEAD)
-          previous=$(git show -s --format=%ci HEAD~1)
+          # Get the tags
+          # Use disabled lines to get last two commits
+          # current=$(git show -s --format=%ci HEAD)
+          # previous=$(git show -s --format=%ci HEAD~1)
+          # git diff --name-only HEAD^ HEAD >> $GITHUB_STEP_SUMMARY
+          version_tag_regex="^v[0-9]+\.[0-9]+\.[0-9]+$" # v0.0.0 
+          tags=$(git tag --sort=-version:refname | \
+            grep -E "${version_tag_regex}" || echo "")
+
+          # Get latest and previous tags
+          latest_tag=$(echo "${tags}" | head -n 1)
+          previous_tag=$(echo "${tags}" | head -n 2 | tail -n 1)
+
+          echo "tags: latest '${latest_tag}', previous '${previous_tag}'"
+
+          # Write to summary
+          error_msg="No files to output. Tag not found:"
           echo ${{ steps.step_states.outputs.summary }} >> $GITHUB_STEP_SUMMARY
-          echo "### Changed files on '${{ github.ref }}':" >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-          echo "Current Commit: ${current}" >> $GITHUB_STEP_SUMMARY
-          echo "Previous Commit: ${previous}" >> $GITHUB_STEP_SUMMARY
-          git diff --name-only HEAD^ HEAD >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo "## Changed files on '${{ inputs.branch_to_summarize }}'" >> $GITHUB_STEP_SUMMARY
+
+          if [ -z "${latest_tag}" ]; then
+            echo "${error_msg} latest" >> $GITHUB_STEP_SUMMARY
+          elif [ -z "${previous_tag}" ]; then
+            echo "${error_msg} previous" >> $GITHUB_STEP_SUMMARY
+          elif [ "${latest_tag}" == "${previous_tag}" ]; then
+            echo "Latest and previous tags are the same: '${latest_tag}'" >> $GITHUB_STEP_SUMMARY
+          else
+            # Get commit dates and hashes
+            latest_date=$(git log -1 --format=%ci $latest_tag)
+            previous_date=$(git log -1 --format=%ci $previous_tag)
+            current_hash=$(git rev-parse --short $latest_tag)
+            previous_hash=$(git rev-parse --short $previous_tag)
+
+            # Append summary to the job summary
+            echo "Latest Tag Commit: '${latest_tag}' (${current_hash}) ${latest_date}" >> $GITHUB_STEP_SUMMARY
+            echo "Previous Tag Commit: '${previous_tag}' (${previous_hash}) ${previous_date}" >> $GITHUB_STEP_SUMMARY
+            echo "Files changed:" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            git diff --name-only $previous_tag..$latest_tag >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+          fi
+
+      - name: Output error message in case of failure or cancel
+        if: failure() || cancelled()
+        run: |
+          if [ "${{ job.status }}" == "cancelled" ]; then
+            out_msg="## Workflow was cancelled"
+          else
+            out_msg="## Error in previous step"
+          fi
+          echo $out_msg >> $GITHUB_STEP_SUMMARY
 ...
